[package]
name = "jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
jsonwebtoken = { version = "10.3.0", features = ["aws_lc_rs"] }
jwks = { path = "../jwks" }
serde = "1.0.228"
validation = { path = "../validation" }
