[package]
name = "jwks"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
jsonwebtoken = { version = "10.3.0", features = ["aws_lc_rs"] }
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
